version: '3.8'
services: 
  laravel:
    build: 
      context: .
      dockerfile: Dockerfile
    command: 'php artisan serve -host="0.0.0.0"'
    volumes:
      - .:/app
      - /app/vendor
      - /app/node_modules

    ports:
      - 8000:8000
    depends_on: 
      - mysql

  queue:
    build: 
      context: .
      dockerfile: Dockerfile
    command: 'php artisan queue:work'
    depends_on: 
      - mysql        

  mysql:
    platform: linux/x86_64
    image: mysql:8.0
    environment: 
      MYSQL_DATABASE: main
      MYSQL_USER: admin
      MYSQL_ROOT: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./storage/dbdata:/var/lib/mysql
    ports:
      - 3306:3306
